#!/usr/bin/env node
// Phase 2 end-to-end: ECHO's avatars as OpenClaw agents, against the real
// gateway, with the built extension in headless Chrome for Testing and real
// model turns.
//
//   1. the setup script, generated by the extension itself, configures the gateway
//   2. ECHO pairs (approved here, on the local test gateway) and forgets the shared token
//   3. each of the eight agents sees only its own tools
//   4. two avatars answer from their own tabs at the same time
//   5. placing an order asks for approval; denied, the order is not placed
//   6. stopping an avatar stops its run: nothing arrives afterwards
//   7. with the gateway down the built-in brain answers; when it returns ECHO reconnects
//
//   npm run build && node tools/openclaw/agents-e2e.cjs
// Needs the "echo" gateway profile running on 127.0.0.1:18790 with a model configured.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const crypto = require('node:crypto');
const { spawn, execFileSync } = require('node:child_process');
const ts = require('typescript');
const { launchEcho, evaluate, findTarget, delay, root } = require('../e2e/chrome.cjs');

require.extensions['.ts'] = (module, filename) => {
  module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }, fileName: filename,
  }).outputText, filename);
};
const { createGatewayConnection } = require(path.join(root, 'src/background/openclaw/connection.ts'));
const { deviceIdentity } = require(path.join(root, 'src/background/openclaw/identity.ts'));
const { keyStore, tokenStore, operatorClient } = require('./probe-identity.cjs');

const OPENCLAW = path.join(os.homedir(), '.npm-global/bin/openclaw');
const URL_ = 'ws://127.0.0.1:18790';
const FIXTURES = path.join(root, 'tools/echobench/fixtures');
const results = [];
const check = (name, ok, detail = '') => { results.push(ok); console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? `  — ${detail}` : ''}`); };
const log = (...a) => console.log('     ', ...a);
const oc = (...args) => execFileSync(OPENCLAW, ['--profile', 'echo', ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
const tryOc = (...args) => { try { oc(...args); return true; } catch { return false; } };
const sharedToken = () => JSON.parse(fs.readFileSync(path.join(os.homedir(), '.openclaw-echo/openclaw.json'), 'utf8')).gateway.auth.token;
const gatewayUp = () => { try { execFileSync('lsof', ['-iTCP:18790', '-sTCP:LISTEN'], { stdio: 'ignore' }); return true; } catch { return false; } };

async function waitFor(fn, timeoutMs, stepMs = 500) {
  for (const started = Date.now(); Date.now() - started < timeoutMs; await delay(stepMs)) {
    const value = await fn().catch(() => null);
    if (value) return value;
  }
  return null;
}

function approvePending() {
  try {
    const devices = JSON.parse(oc('devices', 'list', '--json'));
    for (const req of devices.pending || []) if (/ECHO/.test(JSON.stringify(req))) tryOc('devices', 'approve', req.requestId);
  } catch { /* retry next round */ }
  try {
    const nodes = JSON.parse(oc('nodes', 'pending', '--json'));
    for (const req of nodes.pending || nodes || []) { const id = req.requestId || req.id; if (id && /ECHO/.test(JSON.stringify(req))) tryOc('nodes', 'approve', id); }
  } catch { /* retry next round */ }
}

function startGateway() {
  const logFile = fs.openSync(path.join(os.tmpdir(), 'echo-gateway.log'), 'a');
  const child = spawn(OPENCLAW, ['--profile', 'echo', 'gateway', 'run'], {
    env: { ...process.env, PATH: `${path.dirname(OPENCLAW)}:${process.env.PATH}` }, detached: true, stdio: ['ignore', logFile, logFile],
  });
  child.unref();
}

async function main() {
  if (!gatewayUp()) throw new Error('Start the gateway first: openclaw --profile echo gateway run');
  const server = http.createServer((req, res) => {
    const file = path.join(FIXTURES, path.basename(new URL(req.url, 'http://x').pathname));
    if (!fs.existsSync(file)) { res.writeHead(404); res.end(); return; }
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' });
    res.end(fs.readFileSync(file));
  });
  await new Promise(r => server.listen(0, '127.0.0.1', r));
  const base = `http://127.0.0.1:${server.address().port}`;

  const { cdp, extensionId, worker, browser, cleanup } = await launchEcho({ urls: [`${base}/shop.html`, `${base}/policy.html`] });
  let echoNodeId = null;
  process.on('exit', () => { if (echoNodeId) tryOc('devices', 'remove', echoNodeId); cleanup(); server.close(); });
  log(browser);
  const inWorker = expr => evaluate(cdp, worker.targetId, expr);

  const { targetId: panelId } = await cdp.send('Target.createTarget', { url: `chrome-extension://${extensionId}/sidepanel.html` });
  await findTarget(cdp, t => t.targetId === panelId);
  await delay(800);
  const panelEval = expr => evaluate(cdp, panelId, expr);
  const panel = msg => panelEval(`chrome.runtime.sendMessage(${JSON.stringify(msg)})`);
  await panelEval(`(() => { window.__approvals = 0; chrome.runtime.onMessage.addListener(m => {
    if (m.type === 'ECHO_APPROVAL_REQUEST') { window.__approvals++; chrome.runtime.sendMessage({ type: 'ECHO_APPROVAL_RESPONSE', id: m.id, approved: false }); } }); return true; })()`);

  // 1. The extension writes the gateway setup; run it for real.
  const { script } = await panel({ type: 'ECHO_OPENCLAW_SETUP_SCRIPT' });
  const scriptFile = path.join(os.tmpdir(), `echo-setup-${process.pid}.sh`);
  fs.writeFileSync(scriptFile, script);
  let setupOk = false;
  try { execFileSync('bash', [scriptFile], { env: { ...process.env, OPENCLAW }, stdio: 'ignore' }); setupOk = true; } catch (e) { log(e.message); }
  fs.rmSync(scriptFile, { force: true });
  const configured = JSON.parse(fs.readFileSync(path.join(os.homedir(), '.openclaw-echo/openclaw.json'), 'utf8'));
  check('the generated setup script configures the gateway', setupOk
    && configured.gateway.nodes.commands.allow.length === 96
    && ['echo', 'echo-style', 'echo-officer', 'echo-patrol', 'echo-mentor', 'echo-visionary', 'echo-analyst', 'echo-core'].every(id => configured.agents.entries[id])
    && fs.readFileSync(path.join(os.homedir(), '.openclaw-echo/workspace-echo-analyst/AGENTS.md'), 'utf8').includes('Never fill gaps from memory'),
    `${configured.gateway.nodes.commands.allow.length} commands, ${Object.keys(configured.agents.entries).length} agent entries`);

  // 2. Enable, pair, forget the shared token.
  await panel({ type: 'ECHO_OPENCLAW_SAVE', enabled: true, url: URL_, sharedToken: sharedToken() });
  const status = () => panel({ type: 'ECHO_OPENCLAW_STATUS' }).then(r => r.status);
  let rounds = 0;
  const ready = await waitFor(async () => { if (++rounds % 4 === 0) approvePending(); const s = await status(); return s.ready ? s : null; }, 120_000);
  check('ECHO pairs and becomes ready', !!ready, ready ? `gateway ${ready.serverVersion}` : JSON.stringify(await status()));
  const tokenGone = await waitFor(async () => !(await status()).hasToken, 10_000);
  check('the shared gateway token is deleted once paired', !!tokenGone);
  // 3. Each agent sees only its own tools.
  const operator = createGatewayConnection({ url: URL_, role: 'operator', sharedToken: sharedToken(), client: operatorClient,
    scopes: ['operator.read', 'operator.write'], identity: () => deviceIdentity(keyStore), tokenStore,
    createWebSocket: u => new WebSocket(u, { headers: { Origin: `chrome-extension://${extensionId}` } }) });
  operator.start();
  await waitFor(async () => operator.connected, 15_000, 100);
  // The extension's node, so this run's throwaway device can be removed afterwards.
  const probeId = (await deviceIdentity(keyStore)).deviceId;
  echoNodeId = ((await operator.request('node.list', {})).nodes || [])
    .find(n => n.connected && n.displayName === 'ECHO (Chrome)' && n.nodeId !== probeId)?.nodeId || null;
  const tag = crypto.randomBytes(3).toString('hex');
  const avatars = [['echo', 'echo'], ['echo-style', 'style'], ['echo-officer', 'officer'], ['echo-patrol', 'patrol'],
    ['echo-mentor', 'mentor'], ['echo-visionary', 'visionary'], ['echo-analyst', 'analyst'], ['echo-core', 'core']];
  const isolation = [];
  for (const [agentId, slug] of avatars) {
    const key = `agent:${agentId}:e2e-${tag}`;
    await operator.request('sessions.create', { key, agentId, idempotencyKey: key });
    const eff = await operator.request('tools.effective', { agentId, sessionKey: key });
    const names = (eff.groups || []).flatMap(g => g.tools.map(t => t.id));
    isolation.push(names.length === 11 && names.every(n => n.startsWith(`${slug}_`)));
  }
  check('each of the eight agents sees only its own eleven tools', isolation.every(Boolean), isolation.map(ok => (ok ? '✓' : '✗')).join(''));

  // 4. Two avatars at once, each answering from its own tab.
  const tabs = await inWorker(`chrome.tabs.query({ url: '${base}/*' }).then(t => t.map(x => ({ id: x.id, url: x.url })))`);
  const shopTab = tabs.find(t => t.url.endsWith('/shop.html')).id;
  const policyTab = tabs.find(t => t.url.endsWith('/policy.html')).id;
  await panel({ type: 'ECHO_AGENT_ASSIGN', agent: 'echo-analyst', tabId: shopTab });
  await panel({ type: 'ECHO_AGENT_ASSIGN', agent: 'echo-style', tabId: policyTab });
  const thread = agent => panel({ type: 'ECHO_AGENT_THREAD', agent }).then(r => (r.messages || []).filter(m => m.role === 'echo').map(m => m.text));
  const working = agent => panel({ type: 'ECHO_TASK_STATUS_REQUEST', agent }).then(r => !!r.active);
  const started = Date.now();
  await panel({ type: 'USER_INPUT', agent: 'echo-analyst', text: 'What does the Steel Kettle cost on this page? Check with your tools.' });
  await panel({ type: 'USER_INPUT', agent: 'echo-style', text: 'How many days do I have to return an item, according to this page?' });
  const both = await waitFor(async () => {
    const [a, s] = await Promise.all([thread('echo-analyst'), thread('echo-style')]);
    return a.some(t => /24\.50/.test(t)) && s.some(t => /30/.test(t)) ? { a, s } : null;
  }, 180_000, 1000);
  check('two avatars answer from their own tabs at the same time', !!both,
    both ? `${Math.round((Date.now() - started) / 1000)}s · analyst: "${both.a.at(-1).slice(0, 60)}" · style: "${both.s.at(-1).slice(0, 60)}"`
      : JSON.stringify({ a: await thread('echo-analyst'), s: await thread('echo-style') }).slice(0, 300));

  // 5. Placing an order asks first; denied, nothing is ordered.
  const before = (await thread('echo-analyst')).length;
  await panel({ type: 'USER_INPUT', agent: 'echo-analyst', text: 'Add the Glass Kettle to the cart, go to checkout and place the order.' });
  const replied = await waitFor(async () => !(await working('echo-analyst')) && (await thread('echo-analyst')).length > before, 240_000, 1000);
  const approvals = await panelEval('window.__approvals');
  const ordered = await evaluate(cdp, (await findTarget(cdp, t => t.type === 'page' && t.url.startsWith(base))).targetId, `localStorage.getItem('ordered')`);
  check('placing an order asks for approval, and a denial means no order', !!replied && approvals >= 1 && ordered === null,
    `approvals asked: ${approvals}, ordered: ${ordered}, reply: "${(await thread('echo-analyst')).at(-1)?.slice(0, 90)}"`);

  // 6. Stopping a run stops it here and on the gateway.
  const beforeStop = (await thread('echo-analyst')).length;
  await panel({ type: 'USER_INPUT', agent: 'echo-analyst', text: 'Open every product on this shop one by one and write a detailed review of each.' });
  await waitFor(() => working('echo-analyst'), 10_000);
  await delay(4000);
  await panel({ type: 'ECHO_ABORT', agent: 'echo-analyst' });
  const idle = await waitFor(async () => !(await working('echo-analyst')), 10_000);
  await delay(12_000);
  const afterStop = (await thread('echo-analyst')).length;
  check('stopping an avatar ends its run; nothing arrives afterwards', !!idle && afterStop === beforeStop, `replies after stop: ${afterStop - beforeStop}`);

  // 7. Gateway down: the built-in brain answers. Gateway back: ECHO reconnects.
  operator.stop();
  const pid = execFileSync('lsof', ['-t', '-iTCP:18790', '-sTCP:LISTEN'], { encoding: 'utf8' }).trim().split('\n')[0];
  process.kill(Number(pid));
  await waitFor(async () => !(await status()).ready, 15_000);
  const beforeDown = (await thread('echo-style')).length;
  await panel({ type: 'USER_INPUT', agent: 'echo-style', text: 'Summarize this page.' });
  const fallback = await waitFor(async () => {
    const t = await thread('echo-style');
    return t.length > beforeDown ? t.at(-1) : null;
  }, 20_000);
  check('with the gateway down, the built-in brain answers instead', !!fallback && !/^(TITLE|TEXT):/.test(fallback), fallback?.slice(0, 80));
  startGateway();
  const back = await waitFor(async () => { const s = await status(); return s.ready ? s : null; }, 90_000, 1000);
  check('when the gateway returns, ECHO reconnects by itself', !!back);

  cdp.close();
  const failed = results.filter(ok => !ok).length;
  console.log(`\n${results.length - failed}/${results.length} checks passed`);
  process.exit(failed ? 1 : 0);
}

main().catch(error => { console.error('\nE2E failed:', error.stack || error.message); process.exit(1); });
